CREATE TABLE IF NOT EXISTS ventas (
 id BIGINT PRIMARY KEY AUTO_INCREMENT,
 cliente_id BIGINT NOT NULL,
 fecha DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 medio_pago VARCHAR(30) NOT NULL,
 total DECIMAL(12,2) NOT NULL,
 estado VARCHAR(30) NOT NULL DEFAULT 'REGISTRADA'
);
CREATE TABLE IF NOT EXISTS detalle_venta (
 id BIGINT PRIMARY KEY AUTO_INCREMENT,
 venta_id BIGINT NOT NULL,
 producto_id BIGINT NOT NULL,
 cantidad INT NOT NULL,
 precio_unitario DECIMAL(10,2) NOT NULL,
 subtotal DECIMAL(12,2) NOT NULL,
 CONSTRAINT fk_detalle_venta FOREIGN KEY (venta_id) REFERENCES ventas(id)
);
