  server:
    port: 8089

  spring:
    application:
      name: inventario-service

    datasource:
      url: jdbc:mysql://localhost:3306/vetcontrol_inventario?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      username: vetcontrol
      password: vetcontrol123

    jpa:
      open-in-view: false
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true

    flyway:
      enabled: true
      baseline-on-migrate: true

  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/

  security:
    jwt:
      secret: ${JWT_SECRET:vetcontrol-secret-key-2026-vetcontrol-secret-key-2026}

  logging:
    level:
      cl.duoc.vetcontrol: INFO

  springdoc:
    swagger-ui:
      path: /swagger-ui.html

  management:
    endpoints:
      web:
        exposure:
          include: health,info

