CREATE TABLE IF NOT EXISTS notificaciones (
 id BIGINT PRIMARY KEY AUTO_INCREMENT,
 tipo VARCHAR(60) NOT NULL,
 mensaje VARCHAR(500) NOT NULL,
 fecha DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 leida BOOLEAN NOT NULL DEFAULT FALSE
);
